route:
  receiver: "slack-notifs"
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 30m

receivers:
  - name: "slack-notifs"
    slack_configs:
      - send_resolved: true
        channel: "#ops-alerts"
        username: "prom-alerts"
        api_url: "https://hooks.slack.com/services/TXXX/BYYY/ZZZ"
        title: "{{ .CommonAnnotations.summary }}"
        text: "{{ .CommonAnnotations.description }}"
